version: "2.4"
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    env_file: .env
    volumes:
      - /app/node_modules
      - ./api:/app
    depends_on:
      - mongo

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  mongo:
    image: "mongo"
    ports:
      - 27017:27017
    restart: always

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "4000:80"
    depends_on:
      - api
      - client
